# Generated by Django 5.0.3 on 2024-11-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientsob',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('clientsobcode', models.IntegerField()),
                ('clientsobclientcode', models.IntegerField()),
                ('clientsobsobcode', models.IntegerField()),
                ('clientsobremarks', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'clientsob',
            },
        ),
        migrations.CreateModel(
            name='historyclientsob',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('clientsobcode', models.IntegerField()),
                ('clientsobclientcode', models.IntegerField()),
                ('clientsobsobcode', models.IntegerField()),
                ('clientsobremarks', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'historyclientsob',
                'indexes': [models.Index(fields=['recordno'], name='clientsobh_idx')],
            },
        ),
    ]
