# Generated by Django 5.1 on 2024-11-13 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Franchisestatus_app', '0003_alter_franchisestatus_franchisestatusid'),
        ('MeansofFranchise_app', '0002_alter_meansoffranchise_meansofknowingid'),
    ]

    operations = [
        migrations.CreateModel(
            name='franchise',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('franchisecode', models.IntegerField()),
                ('clientname', models.CharField(max_length=200)),
                ('clientshortname', models.CharField(max_length=200)),
                ('clientclassificationcode', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('contactnumber', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('contactperson', models.CharField(max_length=200)),
                ('contactpersondesignation', models.CharField(max_length=200)),
                ('signatoryname', models.CharField(max_length=200)),
                ('signatorydesignation', models.CharField(max_length=200)),
                ('totalmembers', models.IntegerField()),
                ('totaldependents', models.IntegerField()),
                ('totalemployees', models.IntegerField()),
                ('existinghmo', models.CharField(max_length=200)),
                ('sobtypeid', models.IntegerField()),
                ('referredby', models.CharField(max_length=200)),
                ('disapprovalreason', models.CharField(max_length=200)),
                ('istpa', models.CharField(max_length=200)),
                ('adminfee', models.CharField(max_length=200)),
                ('networkaccessfee', models.CharField(max_length=200)),
                ('locationcode', models.IntegerField()),
                ('remarks', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
                ('franchisestatusid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Franchisestatus_app.franchisestatus', to_field='franchisestatusid')),
                ('meansofknowingid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MeansofFranchise_app.meansoffranchise', to_field='meansofknowingid')),
            ],
            options={
                'db_table': 'franchise',
            },
        ),
        migrations.CreateModel(
            name='historyfranchise',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('franchisecode', models.IntegerField()),
                ('clientname', models.CharField(max_length=200)),
                ('clientshortname', models.CharField(max_length=200)),
                ('clientclassificationcode', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('contactnumber', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('contactperson', models.CharField(max_length=200)),
                ('contactpersondesignation', models.CharField(max_length=200)),
                ('signatoryname', models.CharField(max_length=200)),
                ('signatorydesignation', models.CharField(max_length=200)),
                ('totalmembers', models.IntegerField()),
                ('totaldependents', models.IntegerField()),
                ('totalemployees', models.IntegerField()),
                ('existinghmo', models.CharField(max_length=200)),
                ('sobtypeid', models.IntegerField()),
                ('referredby', models.CharField(max_length=200)),
                ('disapprovalreason', models.CharField(max_length=200)),
                ('istpa', models.CharField(max_length=200)),
                ('adminfee', models.CharField(max_length=200)),
                ('networkaccessfee', models.CharField(max_length=200)),
                ('locationcode', models.IntegerField()),
                ('remarks', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
                ('franchisestatusid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Franchisestatus_app.franchisestatus', to_field='franchisestatusid')),
                ('meansofknowingid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MeansofFranchise_app.meansoffranchise', to_field='meansofknowingid')),
            ],
            options={
                'db_table': 'historyfranchise',
                'indexes': [models.Index(fields=['recordno'], name='franchiserecordh_idx')],
            },
        ),
    ]
