# Generated by Django 5.1 on 2024-11-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='franchisecode',
            field=models.IntegerField(unique=True),
        ),
    ]
