# Generated by Django 5.0.2 on 2024-11-13 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_alter_client_clientcode_and_more'),
        ('clientbranch_app', '0001_initial'),
        ('clientstatus_app', '0002_rename_clientstatusremarks_clientstatus_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('branchcode', models.IntegerField(unique=True)),
                ('branchname', models.CharField(max_length=100)),
                ('branchshortname', models.CharField(max_length=100)),
                ('tin', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('locationcode', models.IntegerField()),
                ('contactnumber', models.CharField(max_length=100)),
                ('emailaddress', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
                ('clientcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client_app.client', to_field='clientcode')),
                ('statuscode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientstatus_app.clientstatus', to_field='clientstatuscode')),
            ],
            options={
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='historybranch',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('branchcode', models.IntegerField()),
                ('branchname', models.CharField(max_length=100)),
                ('branchshortname', models.CharField(max_length=100)),
                ('tin', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('locationcode', models.IntegerField()),
                ('contactnumber', models.CharField(max_length=100)),
                ('emailaddress', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
                ('clientcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client_app.client', to_field='clientcode')),
                ('statuscode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientstatus_app.clientstatus', to_field='clientstatuscode')),
            ],
            options={
                'db_table': 'historybranch',
            },
        ),
        migrations.DeleteModel(
            name='clientbranch',
        ),
        migrations.DeleteModel(
            name='historyclientbranch',
        ),
        migrations.AddIndex(
            model_name='historybranch',
            index=models.Index(fields=['recordno'], name='branchh_idx'),
        ),
    ]
