# Generated by Django 5.0.2 on 2024-11-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCounter',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('countername', models.CharField(max_length=100)),
                ('counterresetbasis', models.CharField(default='Year', max_length=50)),
                ('counter', models.IntegerField(default=0)),
                ('transactdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'CodeCounter',
            },
        ),
    ]
