# Generated by Django 5.0.3 on 2024-11-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='memberstatus',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('memberstatuscode', models.IntegerField()),
                ('memberstatusname', models.CharField(max_length=100)),
                ('memberstatusshortname', models.CharField(max_length=100)),
                ('memberstatusremarks', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'memberstatus',
            },
        ),
        migrations.CreateModel(
            name='historymemberstatus',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('memberstatuscode', models.IntegerField()),
                ('memberstatusname', models.CharField(max_length=100)),
                ('memberstatusshortname', models.CharField(max_length=100)),
                ('memberstatusremarks', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'historymemberstatus',
                'indexes': [models.Index(fields=['recordno'], name='memberstatush_idx')],
            },
        ),
    ]
