# Generated by Django 5.0.2 on 2024-11-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberstatus_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberstatus',
            name='memberstatuscode',
            field=models.IntegerField(unique=True),
        ),
    ]
