# Generated by Django 5.0.2 on 2024-11-20 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_app', '0005_remove_doctor_tin_remove_historydoctor_tin'),
        ('medicalavailmentstatus_app', '0001_initial'),
        ('medicalavailmenttype_app', '0001_initial'),
        ('medicaldiagnosis_app', '0001_initial'),
        ('member_app', '0004_alter_historymember_recordno'),
        ('provider_app', '0002_rename_accreditationdate_historyprovider_accreditdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='approvalCounter',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=2024)),
                ('counter', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='approval',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('approvalcode', models.CharField(max_length=100, unique=True)),
                ('availmentdate', models.DateTimeField()),
                ('callername', models.CharField(max_length=100)),
                ('finaldiagnosis', models.IntegerField()),
                ('idpresented', models.CharField(max_length=100)),
                ('disapproved', models.CharField(max_length=100)),
                ('remarks', models.TextField()),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
                ('availmenttypecode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medicalavailmenttype_app.availmenttype', to_field='availmenttypecode')),
                ('doctorcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctor_app.doctor', to_field='doctorcode')),
                ('initialdiagnosis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medicaldiagnosis_app.diagnosis', to_field='diagnosiscode')),
                ('memberrecordnohist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member_app.historymember')),
                ('policynumber', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member_app.member', to_field='policynumber')),
                ('providercode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='provider_app.provider', to_field='providercode')),
                ('statuscode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medicalavailmentstatus_app.availmentstatus', to_field='availmentstatuscode')),
            ],
            options={
                'db_table': 'approval',
            },
        ),
        migrations.CreateModel(
            name='historyapproval',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('approvalcode', models.CharField(max_length=100)),
                ('availmentdate', models.DateTimeField()),
                ('callername', models.CharField(max_length=100)),
                ('finaldiagnosis', models.IntegerField()),
                ('idpresented', models.CharField(max_length=100)),
                ('disapproved', models.CharField(max_length=100)),
                ('remarks', models.TextField()),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
                ('availmenttypecode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medicalavailmenttype_app.availmenttype', to_field='availmenttypecode')),
                ('doctorcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctor_app.doctor', to_field='doctorcode')),
                ('initialdiagnosis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medicaldiagnosis_app.diagnosis', to_field='diagnosiscode')),
                ('memberrecordnohist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member_app.historymember', to_field='recordno')),
                ('policynumber', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member_app.member', to_field='policynumber')),
                ('providercode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='provider_app.provider', to_field='providercode')),
                ('statuscode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medicalavailmentstatus_app.availmentstatus', to_field='availmentstatuscode')),
            ],
            options={
                'db_table': 'historyapproval',
                'indexes': [models.Index(fields=['recordno'], name='historyapprovalh_idx')],
            },
        ),
    ]
