# Generated by Django 5.0.2 on 2024-11-20 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapproval_app', '0002_alter_approval_finaldiagnosis_and_more'),
        ('member_app', '0005_alter_historymember_recordno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyapproval',
            name='memberrecordnohist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member_app.historymember'),
        ),
    ]
