# Generated by Django 5.0.2 on 2024-11-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapproval_app', '0003_alter_historyapproval_memberrecordnohist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='memberrecordnohist',
        ),
        migrations.RemoveField(
            model_name='historyapproval',
            name='memberrecordnohist',
        ),
    ]
