# Generated by Django 5.0.2 on 2024-11-20 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapproval_app', '0004_remove_approval_memberrecordnohist_and_more'),
        ('medicaldiagnosis_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyapproval',
            name='initialdiagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medicaldiagnosis_app.diagnosis', to_field='diagnosiscode'),
        ),
    ]
