# Generated by Django 5.0.2 on 2024-11-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapproval_app', '0005_alter_historyapproval_initialdiagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyapproval',
            name='initialdiagnosis',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='approvalcounter',
            table='approvalCounter',
        ),
    ]
