# Generated by Django 5.0.2 on 2024-11-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapproval_app', '0006_alter_historyapproval_initialdiagnosis_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='approvalCounter',
        ),
    ]
