# Generated by Django 5.0.2 on 2024-11-21 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapproval_app', '0007_delete_approvalcounter'),
        ('medicaldiagnosis_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='initialdiagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='initialdiagnosis', to='medicaldiagnosis_app.diagnosis', to_field='diagnosiscode'),
        ),
    ]
