# Generated by Django 5.0.2 on 2024-11-22 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapproval_app', '0009_alter_approval_initialdiagnosis'),
        ('medicaldiagnosis_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='finaldiagnosis',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historyapproval',
            name='initialdiagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='initialdiagnosis', to='medicaldiagnosis_app.diagnosis', to_field='diagnosiscode'),
        ),
    ]
