# Generated by Django 5.0.2 on 2024-11-22 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapproval_app', '0011_alter_approval_finaldiagnosis_and_more'),
        ('medicaldiagnosis_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='finaldiagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='finaldiagnosis', to='medicaldiagnosis_app.diagnosis'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='initialdiagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='initialdiagnosis', to='medicaldiagnosis_app.diagnosis'),
        ),
        migrations.AlterField(
            model_name='historyapproval',
            name='finaldiagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='historyfinaldiagnosis', to='medicaldiagnosis_app.diagnosis'),
        ),
        migrations.AlterField(
            model_name='historyapproval',
            name='initialdiagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='historyinitialdiagnosis', to='medicaldiagnosis_app.diagnosis'),
        ),
    ]
