# Generated by Django 5.0.2 on 2024-08-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moduleslist',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('modulecode', models.IntegerField()),
                ('modulename', models.CharField(max_length=100)),
                ('moduleshortname', models.CharField(max_length=100)),
                ('moduleappname', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'moduleslist',
            },
        ),
        migrations.CreateModel(
            name='historymoduleslist',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('modulecode', models.IntegerField()),
                ('modulename', models.CharField(max_length=100)),
                ('moduleshortname', models.CharField(max_length=100)),
                ('moduleappname', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'historymoduleslist',
                'indexes': [models.Index(fields=['recordno'], name='moduleslistrecordh_idx')],
            },
        ),
    ]
