# Generated by Django 5.0.2 on 2024-10-28 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natureofmembership_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='natureofmembership',
            table='NatureOfMembership',
        ),
    ]
