# Generated by Django 5.0.2 on 2024-10-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeansofFranchise',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('meansofknowingid', models.IntegerField()),
                ('means', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'MeansofFranchise',
            },
        ),
        migrations.CreateModel(
            name='historymeansoffranchise',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('meansofknowingid', models.IntegerField()),
                ('means', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'historymeansoffranchise',
                'indexes': [models.Index(fields=['recordno'], name='meansofknowingidrecordh_idx')],
            },
        ),
    ]
