# Generated by Django 5.0.2 on 2024-11-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientclassification',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('clientclassificationcode', models.IntegerField()),
                ('clientclassificationname', models.CharField(max_length=100)),
                ('clientclassificationremarks', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'clientclassification',
            },
        ),
        migrations.CreateModel(
            name='historyclientclassification',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('clientclassificationcode', models.IntegerField()),
                ('clientclassificationname', models.CharField(max_length=100)),
                ('clientclassificationremarks', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'historyclientclassification',
                'indexes': [models.Index(fields=['recordno'], name='clientclassificationh_idx')],
            },
        ),
    ]
