# Generated by Django 5.0.2 on 2024-11-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientclassification_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientclassification',
            name='clientclassificationcode',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='historyclientclassification',
            name='clientclassificationcode',
            field=models.IntegerField(unique=True),
        ),
    ]
