# Generated by Django 5.0.2 on 2024-11-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientclassification_app', '0002_alter_clientclassification_clientclassificationcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyclientclassification',
            name='clientclassificationcode',
            field=models.IntegerField(),
        ),
    ]
