# Generated by Django 5.0.2 on 2024-08-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historyroles',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('roleid', models.IntegerField()),
                ('rolename', models.CharField(max_length=200)),
                ('roledisplayname', models.CharField(max_length=200)),
                ('roledescription', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'historyroles',
            },
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('roleid', models.IntegerField(unique=True)),
                ('rolename', models.CharField(max_length=200)),
                ('roledisplayname', models.CharField(max_length=200)),
                ('roledescription', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
    ]
