# Generated by Django 5.0.2 on 2024-08-14 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider_app', '__first__'),
        ('specialization_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('doctorcode', models.IntegerField(unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('tin', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=100)),
                ('landlinenumber', models.CharField(max_length=100)),
                ('emailaddres', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('professionalfee', models.CharField(max_length=100)),
                ('doctorstatuscode', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
                ('locationcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='provider_app.provider', to_field='locationcode')),
                ('specializationcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='specialization_app.specialization', to_field='specializationcode')),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='historydoctor',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('doctorcode', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('tin', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=100)),
                ('landlinenumber', models.CharField(max_length=100)),
                ('emailaddres', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('professionalfee', models.CharField(max_length=100)),
                ('doctorstatuscode', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
                ('locationcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='provider_app.provider', to_field='locationcode')),
                ('specializationcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='specialization_app.specialization', to_field='specializationcode')),
            ],
            options={
                'db_table': 'historydoctor',
                'indexes': [models.Index(fields=['recordno'], name='doctorrecordh_idx')],
            },
        ),
    ]
