# Generated by Django 5.0.2 on 2024-08-14 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
        ('doctorstatus_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctorstatuscode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctorstatus_app.doctorstatus', to_field='doctorstatuscode'),
        ),
        migrations.AlterField(
            model_name='historydoctor',
            name='doctorstatuscode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctorstatus_app.doctorstatus', to_field='doctorstatuscode'),
        ),
    ]
