# Generated by Django 5.0.2 on 2024-08-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0002_alter_doctor_doctorstatuscode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='accreditdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='disaccreditdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='reaccreditdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historydoctor',
            name='accreditdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historydoctor',
            name='disaccreditdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historydoctor',
            name='reaccreditdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
