# Generated by Django 5.0.3 on 2024-10-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0003_doctor_accreditdate_doctor_disaccreditdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='subspecializationcode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historydoctor',
            name='subspecializationcode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
