# Generated by Django 5.1 on 2024-11-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0004_doctor_subspecializationcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='tin',
        ),
        migrations.RemoveField(
            model_name='historydoctor',
            name='tin',
        ),
    ]
