# Generated by Django 5.0.2 on 2024-11-08 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membergender_app', '0002_alter_membergender_membergendercode'),
        ('memberstatus_app', '0002_alter_memberstatus_memberstatuscode'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('membercode', models.IntegerField()),
                ('policynumber', models.CharField(max_length=255)),
                ('thirdpartyid', models.CharField(max_length=255)),
                ('otherid', models.CharField(max_length=255)),
                ('clientcode', models.CharField(max_length=255)),
                ('branchcode', models.IntegerField()),
                ('membertypecode', models.IntegerField()),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('middlename', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('enrollage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('civilstatuscode', models.IntegerField()),
                ('effectivedate', models.DateTimeField()),
                ('expirydate', models.DateTimeField()),
                ('renewaldate', models.DateTimeField(blank=True, null=True)),
                ('reinstateddate', models.DateTimeField(blank=True, null=True)),
                ('cancellationdate', models.DateTimeField(blank=True, null=True)),
                ('hib', models.IntegerField()),
                ('covid', models.IntegerField()),
                ('tin', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('locationcode', models.IntegerField()),
                ('contactnumber', models.CharField(max_length=255)),
                ('emailaddress', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
                ('gendercode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='membergender_app.membergender', to_field='membergendercode')),
                ('statuscode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='memberstatus_app.memberstatus', to_field='memberstatuscode')),
            ],
        ),
        migrations.CreateModel(
            name='historymember',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('membercode', models.IntegerField()),
                ('policynumber', models.CharField(max_length=255)),
                ('thirdpartyid', models.CharField(max_length=255)),
                ('otherid', models.CharField(max_length=255)),
                ('clientcode', models.CharField(max_length=255)),
                ('branchcode', models.IntegerField()),
                ('membertypecode', models.IntegerField()),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('middlename', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('enrollage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('civilstatuscode', models.IntegerField()),
                ('effectivedate', models.DateTimeField()),
                ('expirydate', models.DateTimeField()),
                ('renewaldate', models.DateTimeField(blank=True, null=True)),
                ('reinstateddate', models.DateTimeField(blank=True, null=True)),
                ('cancellationdate', models.DateTimeField(blank=True, null=True)),
                ('hib', models.IntegerField()),
                ('covid', models.IntegerField()),
                ('tin', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('locationcode', models.IntegerField()),
                ('contactnumber', models.CharField(max_length=255)),
                ('emailaddress', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
                ('gendercode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='membergender_app.membergender', to_field='membergendercode')),
                ('statuscode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='memberstatus_app.memberstatus', to_field='memberstatuscode')),
            ],
            options={
                'db_table': 'historymember',
                'indexes': [models.Index(fields=['recordno'], name='memberh_idx')],
            },
        ),
    ]
