# Generated by Django 5.0.2 on 2024-11-13 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='member',
        ),
    ]
