# Generated by Django 5.0.2 on 2024-11-15 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0006_alter_client_clientcode_and_more'),
        ('clientbranch_app', '0002_branch_historybranch_delete_clientbranch_and_more'),
        ('member_app', '0002_alter_member_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymember',
            name='branchcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientbranch_app.branch', to_field='branchcode'),
        ),
        migrations.AlterField(
            model_name='historymember',
            name='clientcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client_app.client', to_field='clientcode'),
        ),
        migrations.AlterField(
            model_name='historymember',
            name='membercode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='branchcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientbranch_app.branch', to_field='branchcode'),
        ),
        migrations.AlterField(
            model_name='member',
            name='clientcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client_app.client', to_field='clientcode'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membercode',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='policynumber',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
