# Generated by Django 5.0.2 on 2024-11-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0003_alter_historymember_branchcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymember',
            name='recordno',
            field=models.IntegerField(unique=True),
        ),
    ]
