# Generated by Django 5.0.2 on 2024-11-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0004_alter_historymember_recordno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymember',
            name='recordno',
            field=models.IntegerField(),
        ),
    ]
