# Generated by Django 5.0.2 on 2024-08-14 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('department_app', '__first__'),
        ('roles_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userid', models.IntegerField()),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('street_address', models.CharField(blank=True, max_length=300)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('region', models.CharField(blank=True, max_length=300)),
                ('province', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=300)),
                ('barangay', models.CharField(blank=True, max_length=300)),
                ('postal', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(blank=True, max_length=300)),
                ('remarks', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('departmentcode', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department_app.department', to_field='departmentcode')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('roleid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roles_app.roles', to_field='roleid')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='historylogin',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('street_address', models.CharField(blank=True, max_length=300)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('region', models.CharField(blank=True, max_length=300)),
                ('province', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=300)),
                ('barangay', models.CharField(blank=True, max_length=300)),
                ('postal', models.CharField(blank=True, max_length=300)),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
                ('departmentcode', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department_app.department', to_field='departmentcode')),
                ('roleid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roles_app.roles', to_field='roleid')),
            ],
            options={
                'db_table': 'historylogin',
                'indexes': [models.Index(fields=['recordno'], name='loginidh_idx')],
            },
        ),
    ]
