# Generated by Django 5.0.2 on 2024-08-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('departmentcode', models.IntegerField(unique=True)),
                ('departmentname', models.CharField(max_length=100)),
                ('departmentshortname', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='historydepartment',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('departmentcode', models.IntegerField()),
                ('departmentname', models.CharField(max_length=100)),
                ('departmentshortname', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'historydepartment',
                'indexes': [models.Index(fields=['recordno'], name='departmetnrecordh_idx')],
            },
        ),
    ]
