# Generated by Django 5.0.3 on 2024-10-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicalprocedures',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('procedurecode', models.IntegerField()),
                ('procedureabbreviation', models.CharField(max_length=100)),
                ('procedurename', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'medicalprocedures',
            },
        ),
        migrations.CreateModel(
            name='historymedicalprocedures',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('procedurecode', models.IntegerField()),
                ('procedureabbreviation', models.CharField(max_length=100)),
                ('procedurename', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'historymedicalprocedures',
                'indexes': [models.Index(fields=['recordno'], name='medicalproceduresrecordh_idx')],
            },
        ),
    ]
