# Generated by Django 5.0.3 on 2024-11-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sob',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('sobcode', models.IntegerField(unique=True)),
                ('sobname', models.CharField(max_length=255)),
                ('sobshortname', models.CharField(max_length=50, null=True)),
                ('remarks', models.TextField(null=True)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transacttype', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Sob',
                'indexes': [models.Index(fields=['sobcode'], name='sobcode_idx'), models.Index(fields=['sobcode', 'sobname'], name='sobcode_sobname_idx')],
            },
        ),
        migrations.CreateModel(
            name='SobHistory',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('sobcode', models.IntegerField()),
                ('sobname', models.CharField(max_length=255)),
                ('sobshortname', models.CharField(max_length=50, null=True)),
                ('remarks', models.TextField(null=True)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transacttype', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'SobHistory',
                'indexes': [models.Index(fields=['recordno'], name='sobrecordnoh_idx'), models.Index(fields=['sobcode'], name='sobcodeh_idx'), models.Index(fields=['sobcode', 'sobname'], name='sobcode_sobnameh_idx')],
            },
        ),
    ]
