# Generated by Django 5.0.2 on 2024-08-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('categorycode', models.IntegerField(unique=True)),
                ('providercategoryname', models.CharField(max_length=100)),
                ('providercategoryshortname', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('ordernumber', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'category',
                'indexes': [models.Index(fields=['categorycode'], name='categorycodecode_idx'), models.Index(fields=['categorycode', 'providercategoryname'], name='providercategoryname')],
            },
        ),
        migrations.CreateModel(
            name='historycategory',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('categorycode', models.IntegerField()),
                ('providercategoryname', models.CharField(max_length=100)),
                ('providercategoryshortname', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('ordernumber', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'historycategory',
                'indexes': [models.Index(fields=['recordno'], name='categoryrecordh_idx'), models.Index(fields=['categorycode'], name='categorycode_idx'), models.Index(fields=['categorycode', 'providercategoryname'], name='providercategorynameh')],
            },
        ),
    ]
