# Generated by Django 5.0.3 on 2024-11-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='membergender',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('membergendercode', models.IntegerField()),
                ('membergendername', models.CharField(max_length=100)),
                ('membergendershortname', models.CharField(max_length=100)),
                ('membergenderremarks', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'membergender',
            },
        ),
        migrations.CreateModel(
            name='historymembergender',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('membergendercode', models.IntegerField()),
                ('membergendername', models.CharField(max_length=100)),
                ('membergendershortname', models.CharField(max_length=100)),
                ('membergenderremarks', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'historymembergender',
                'indexes': [models.Index(fields=['recordno'], name='membergenderh_idx')],
            },
        ),
    ]
