# Generated by Django 5.0.3 on 2024-10-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roomtype',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('roomcode', models.IntegerField(unique=True)),
                ('roomname', models.CharField(max_length=50)),
                ('roomshortname', models.CharField(max_length=10, null=True)),
                ('remarks', models.TextField(null=True)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transacttype', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'roomtype',
                'indexes': [models.Index(fields=['roomcode'], name='roomcode_idx'), models.Index(fields=['roomcode', 'roomname'], name='roomcode_roomname_idx')],
            },
        ),
        migrations.CreateModel(
            name='roomtypehistory',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('roomcode', models.IntegerField()),
                ('roomname', models.CharField(max_length=50)),
                ('roomshortname', models.CharField(max_length=10, null=True)),
                ('remarks', models.TextField(null=True)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transacttype', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'roomtypehistory',
                'indexes': [models.Index(fields=['recordno'], name='roomrecordnoh_idx'), models.Index(fields=['roomcode'], name='roomcodeh_idx'), models.Index(fields=['roomcode', 'roomname'], name='roomcodeh_roomnmh_idx')],
            },
        ),
    ]
