# Generated by Django 5.0.3 on 2024-10-22 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomtype_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='transacttype',
            new_name='transactype',
        ),
        migrations.RenameField(
            model_name='roomtypehistory',
            old_name='transacttype',
            new_name='transactype',
        ),
    ]
