# Generated by Django 5.0.2 on 2024-08-14 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_app', '0001_initial'),
        ('provider_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='providerdoctors',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('room', models.CharField(max_length=100)),
                ('scheduleday', models.CharField(max_length=100)),
                ('scheduletime', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
                ('doctorcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctor_app.doctor', to_field='doctorcode')),
                ('providercode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='provider_app.provider', to_field='providercode')),
            ],
            options={
                'db_table': 'providerdoctors',
            },
        ),
        migrations.CreateModel(
            name='historyproviderdoctors',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('room', models.CharField(max_length=100)),
                ('scheduleday', models.CharField(max_length=100)),
                ('scheduletime', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
                ('doctorcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctor_app.doctor', to_field='doctorcode')),
                ('providercode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='provider_app.provider', to_field='providercode')),
            ],
            options={
                'db_table': 'historyproviderdoctors',
                'indexes': [models.Index(fields=['recordno'], name='providerdoctorsrecordh_idx')],
            },
        ),
    ]
