# Generated by Django 5.0.2 on 2024-11-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapprovalprocedure_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyapprovalprocedure',
            name='procedurename',
        ),
        migrations.RemoveField(
            model_name='historyapprovalprocedure',
            name='procedureshortname',
        ),
        migrations.AddField(
            model_name='historyapprovalprocedure',
            name='confinementamount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historyapprovalprocedure',
            name='otheramount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historyapprovalprocedure',
            name='professionalfee',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
