# Generated by Django 5.0.2 on 2024-08-14 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department_app', '__first__'),
        ('roles_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='coopagent',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('agentid', models.IntegerField()),
                ('firstname', models.CharField(max_length=200)),
                ('middlename', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('suffix', models.CharField(max_length=200)),
                ('civilstatuscode', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('email', models.CharField(max_length=200)),
                ('mobilenumber', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('locationcode', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
                ('departmentcode', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department_app.department', to_field='departmentcode')),
                ('roleid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roles_app.roles', to_field='roleid')),
            ],
            options={
                'db_table': 'coopagent',
            },
        ),
        migrations.CreateModel(
            name='historycoopagent',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('agentid', models.IntegerField()),
                ('firstname', models.CharField(max_length=200)),
                ('middlename', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('suffix', models.CharField(max_length=200)),
                ('civilstatuscode', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('email', models.CharField(max_length=200)),
                ('mobilenumber', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('locationcode', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
                ('departmentcode', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department_app.department', to_field='departmentcode')),
                ('roleid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roles_app.roles', to_field='roleid')),
            ],
            options={
                'db_table': 'historycoopagent',
                'indexes': [models.Index(fields=['recordno'], name='coopagentrecordh_idx')],
            },
        ),
    ]
