# Generated by Django 5.0.3 on 2024-11-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('clientcode', models.IntegerField()),
                ('clientparentcode', models.IntegerField()),
                ('clientclassificationcode', models.IntegerField()),
                ('clientname', models.CharField(max_length=100)),
                ('clientshortname', models.CharField(max_length=100)),
                ('clientsubscriptiondate', models.DateTimeField()),
                ('clienteffectivedate', models.DateTimeField()),
                ('clientexpirydate', models.DateTimeField()),
                ('clientrenewaldate', models.DateTimeField()),
                ('clientstatuscode', models.IntegerField()),
                ('clientregistrationnumber', models.IntegerField()),
                ('clientgascheduledate', models.DateTimeField()),
                ('clienttin', models.CharField(max_length=100)),
                ('clientaddress', models.CharField(max_length=100)),
                ('clientlocationcode', models.IntegerField()),
                ('clientcontactnumber', models.CharField(max_length=100)),
                ('clientemailaddress', models.CharField(max_length=100)),
                ('clientremarks', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='historyclient',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('clientcode', models.IntegerField()),
                ('clientparentcode', models.IntegerField()),
                ('clientclassificationcode', models.IntegerField()),
                ('clientname', models.CharField(max_length=100)),
                ('clientshortname', models.CharField(max_length=100)),
                ('clientsubscriptiondate', models.DateTimeField()),
                ('clienteffectivedate', models.DateTimeField()),
                ('clientexpirydate', models.DateTimeField()),
                ('clientrenewaldate', models.DateTimeField()),
                ('clientstatuscode', models.IntegerField()),
                ('clientregistrationnumber', models.IntegerField()),
                ('clientgascheduledate', models.DateTimeField()),
                ('clienttin', models.CharField(max_length=100)),
                ('clientaddress', models.CharField(max_length=100)),
                ('clientlocationcode', models.IntegerField()),
                ('clientcontactnumber', models.CharField(max_length=100)),
                ('clientemailaddress', models.CharField(max_length=100)),
                ('clientremarks', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'historyclient',
                'indexes': [models.Index(fields=['recordno'], name='clienth_idx')],
            },
        ),
    ]
