# Generated by Django 5.0.2 on 2024-11-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientcode',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='historyclient',
            name='clientcode',
            field=models.IntegerField(unique=True),
        ),
    ]
