# Generated by Django 5.0.2 on 2024-11-13 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_rename_clientaddress_client_address_and_more'),
        ('clientclassification_app', '0002_alter_clientclassification_clientclassificationcode_and_more'),
        ('clientstatus_app', '0002_rename_clientstatusremarks_clientstatus_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='statuscode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientstatus_app.clientstatus', to_field='clientstatuscode'),
        ),
        migrations.AlterField(
            model_name='historyclient',
            name='clientclassificationcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientclassification_app.clientclassification', to_field='clientclassificationcode'),
        ),
        migrations.AlterField(
            model_name='historyclient',
            name='statuscode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientstatus_app.clientstatus', to_field='clientstatuscode'),
        ),
    ]
