# Generated by Django 5.0.2 on 2024-11-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_alter_client_statuscode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyclient',
            name='clientcode',
            field=models.IntegerField(),
        ),
    ]
