# Generated by Django 5.0.2 on 2024-11-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_alter_historyclient_clientcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientcode',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='historyclient',
            name='clientcode',
            field=models.CharField(max_length=100),
        ),
    ]
