# Generated by Django 5.0.2 on 2024-08-14 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='payableName',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('payablenameid', models.IntegerField()),
                ('payablename', models.CharField(max_length=100)),
                ('daystype', models.CharField(max_length=100)),
                ('numberofdays', models.IntegerField()),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
                ('providercode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='provider_app.provider', to_field='providercode')),
            ],
            options={
                'db_table': 'payableName',
            },
        ),
        migrations.CreateModel(
            name='historypayableName',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('payablenameid', models.IntegerField()),
                ('payablename', models.CharField(max_length=100)),
                ('daystype', models.CharField(max_length=100)),
                ('numberofdays', models.IntegerField()),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
                ('providercode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='provider_app.provider', to_field='providercode')),
            ],
            options={
                'db_table': 'historypayableName',
                'indexes': [models.Index(fields=['recordno'], name='payableNamerecordh_idx')],
            },
        ),
    ]
