# Generated by Django 5.0.2 on 2024-08-14 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_app', '0001_initial'),
        ('providerstatus_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='historyprovider',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('providercode', models.IntegerField()),
                ('providername', models.CharField(max_length=100)),
                ('tin', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('locationcode', models.IntegerField()),
                ('emailaddress', models.CharField(max_length=100)),
                ('contactperson', models.CharField(max_length=100)),
                ('landline', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=100)),
                ('accreditationdate', models.DateField(blank=True, null=True)),
                ('suspensiondate', models.DateField(blank=True, null=True)),
                ('disaccreditationdate', models.DateField(blank=True, null=True)),
                ('reaccreditationdate', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
                ('categorycode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='category_app.category', to_field='categorycode')),
                ('providerstatuscode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='providerstatus_app.providerstatus', to_field='providerstatuscode')),
            ],
            options={
                'db_table': 'historyprovider',
                'indexes': [models.Index(fields=['recordno'], name='providerrecordh_idx'), models.Index(fields=['locationcode'], name='locationcodeh_idx'), models.Index(fields=['locationcode', 'address'], name='addressh')],
            },
        ),
        migrations.CreateModel(
            name='provider',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('providercode', models.IntegerField(unique=True)),
                ('providername', models.CharField(max_length=100)),
                ('tin', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('locationcode', models.IntegerField(unique=True)),
                ('emailaddress', models.CharField(max_length=100)),
                ('contactperson', models.CharField(max_length=100)),
                ('landline', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=100)),
                ('accreditationdate', models.DateField(blank=True, null=True)),
                ('suspensiondate', models.DateField(blank=True, null=True)),
                ('disaccreditationdate', models.DateField(blank=True, null=True)),
                ('reaccreditationdate', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
                ('categorycode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='category_app.category', to_field='categorycode')),
                ('providerstatuscode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='providerstatus_app.providerstatus', to_field='providerstatuscode')),
            ],
            options={
                'db_table': 'provider',
                'indexes': [models.Index(fields=['locationcode'], name='locationcode_idx'), models.Index(fields=['locationcode', 'address'], name='address')],
            },
        ),
    ]
