# Generated by Django 5.0.2 on 2024-11-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientstatus_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientstatus',
            old_name='clientstatusremarks',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='historyclientstatus',
            old_name='clientstatusremarks',
            new_name='remarks',
        ),
        migrations.AlterField(
            model_name='clientstatus',
            name='clientstatuscode',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='historyclientstatus',
            name='clientstatuscode',
            field=models.IntegerField(unique=True),
        ),
    ]
