# Generated by Django 5.1 on 2024-11-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franchisestatus',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('franchisestatusid', models.IntegerField()),
                ('franhcisestatusname', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Franchisestatus',
            },
        ),
        migrations.CreateModel(
            name='historyfranchisestatus',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('franchisestatusid', models.IntegerField()),
                ('franhcisestatusname', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'historyfranchisestatus',
                'indexes': [models.Index(fields=['recordno'], name='franchisestatusidrecordh_idx')],
            },
        ),
    ]
