# Generated by Django 5.0.2 on 2024-11-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diagnosis',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('diagnosiscode', models.IntegerField(unique=True)),
                ('diagnosisname', models.CharField(max_length=100)),
                ('diagnosisshortname', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'diagnosis',
            },
        ),
        migrations.CreateModel(
            name='historydiagnosis',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('diagnosiscode', models.IntegerField()),
                ('diagnosisname', models.CharField(max_length=100)),
                ('diagnosisshortname', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('transactby', models.IntegerField()),
                ('transactdate', models.DateTimeField()),
                ('transactype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'historydiagnosis',
                'indexes': [models.Index(fields=['recordno'], name='diagnosish_idx')],
            },
        ),
    ]
