# Generated by Django 5.0.3 on 2024-10-21 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedureprovider_app', '0002_remove_historyprocedureprovider_procedureprovidercode_and_more'),
        ('provider_app', '0002_rename_accreditationdate_historyprovider_accreditdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyprocedureprovider',
            name='procedureprovidercode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historyprocedureprovider',
            name='providercode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='provider_app.provider', to_field='providercode'),
        ),
    ]
