# Generated by Django 5.0.2 on 2024-08-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='permission',
            fields=[
                ('recordno', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('roleid', models.IntegerField()),
                ('modulecode', models.IntegerField()),
                ('accesscode', models.IntegerField()),
                ('holder', models.IntegerField()),
                ('remarks', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='historypermission',
            fields=[
                ('recordnohist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recordno', models.IntegerField()),
                ('roleid', models.IntegerField()),
                ('modulecode', models.IntegerField()),
                ('accesscode', models.IntegerField()),
                ('holder', models.IntegerField()),
                ('remarks', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'historypermission',
                'indexes': [models.Index(fields=['recordno'], name='permissionrecordh_idx')],
            },
        ),
    ]
